const QUOTATION_TRANSPORT_MODES = ['MARITIMO', 'AEREO', 'TERRESTRE']
const QUOTATION_MODALITIES = ['FCL', 'LCL', 'AEREO', 'NO_APLICA']
const QUOTATION_BUSINESS_TYPES = [
  'AEREO',
  'CORREO',
  'MARITIMO',
  'ALMACENAMIENTO',
  'TERRESTRE',
  'LOGISTICA_CIRCULAR',
  'ASESORIA',
  'IMPORTACIONES',
  'EXPORTACIONES',
  'LOGISTICA_ALMACENAMIENTO',
  'TRANSPORTE',
]
const QUOTATION_MATERIAL_CLASSES = ['NO_PELIGROSO', 'PELIGROSO']
const QUOTATION_STATUSES = [
  'BORRADOR',
  'ENVIADA',
  'APROBADA',
  'RECHAZADA',
  'VENCIDA',
  'CONVERTIDA',
]
const QUOTATION_CLOSURE_STATUSES = ['ABIERTA', 'CIERRE_EXITOSO', 'CIERRE_NO_EXITOSO']
const QUOTATION_SERVICE_CODES = [
  'ADUANA_EXPORTACION',
  'ADUANA_EXTERIOR',
  'ALISTAMIENTO_CARGA',
  'BODEGA_EXTERIOR',
  'BODEGA_ZF',
  'DTA',
  'ETIQUETADO',
  'FLETE_INTERNACIONAL',
  'FLETE_NACIONAL',
  'LIBERACION_BL_GUIA',
  'NACIONALIZACION',
  'OTM',
  'PICKUP',
  'SEGURO',
  'SERVICIOS_EXTERIOR',
  'TERRESTRE_DESTINO',
  'TRANSPORTE_NACIONAL',
  'URBANO',
  'ALISTAMIENTO',
  'ALMACENAMIENTO',
  'ARRENDAMIENTO',
  'CONCESION_ESPACIOS',
  'CUADRILLA_DESCARGUE',
  'MANEJO_INVENTARIOS',
  'USO_INSTAL_CROSS_DOCKING_5_DIAS_LIB',
  'USO_INSTAL_TRANSBORDO_CARRO_A_CARRO',
  'USO_MONTACARGAS',
  'CUORRIER',
  'TERRESTRE',
  'TUNGSTENO',
  'COBALTO',
  '718',
  'OTROS',
  'ASESORIA',
  'COMERCIALIZADORA',
]
const QUOTATION_DOCUMENT_TYPES = [
  'REQUERIMIENTO',
  'SOPORTE',
  'FICHA_TECNICA',
  'FACTURA_COMERCIAL',
  'PACKING_LIST',
  'BL',
  'AWB',
  'SEGURO',
  'MANDATO',
  'CERTIFICADO',
  'COTIZACION_PROVEEDOR',
  'OTRO',
]
const SHIPMENT_OPERATIONAL_STATUSES = [
  'CREADA',
  'OPERACIONES',
  'RESERVADA',
  'EN_TRANSITO',
  'ARRIBADA',
  'NACIONALIZACION',
  'ENTREGADA',
  'FINALIZADA_OPERATIVAMENTE',
  'CANCELADA',
]
const SHIPMENT_FINANCIAL_STATUSES = [
  'PENDIENTE_FACTURACION',
  'FACTURADA_CLIENTE',
  'PENDIENTE_FACTURAS_PROVEEDOR',
  'PENDIENTE_PAGOS',
  'EN_CONCILIACION',
  'RENTABILIDAD_CALCULADA',
  'CIERRE_FINANCIERO',
  'CERRADA',
]
const SHIPMENT_CLOSURE_STATUSES = ['ABIERTO', 'CERRADO']
const SHIPMENT_DOCUMENT_TYPES = [
  'SOPORTE',
  'FICHA_TECNICA',
  'FACTURA_COMERCIAL',
  'PACKING_LIST',
  'BL',
  'AWB',
  'SEGURO',
  'MANDATO',
  'CERTIFICADO',
  'FACTURA_CLIENTE',
  'FACTURA_PROVEEDOR',
  'SOPORTE_PAGO',
  'SOPORTE_CONTABLE',
  'CONCILIACION',
  'OTRO',
]
const SHIPMENT_TASK_STATUSES = [
  'PENDIENTE',
  'EN_PROCESO',
  'COMPLETADA',
  'CANCELADA',
]
const SHIPMENT_TASK_PRIORITIES = ['BAJA', 'MEDIA', 'ALTA', 'CRITICA']
const SHIPMENT_COST_STATUSES = ['ESTIMADO', 'CONFIRMADO', 'FACTURADO', 'PAGADO']
const SHIPMENT_COST_TYPES = [
  'FLETE',
  'ADUANA',
  'TRANSPORTE',
  'SEGURO',
  'BODEGAJE',
  'DOCUMENTACION',
  'DEMORAS',
  'STORAGE',
  'INSPECCION',
  'OTROS',
]
const SHIPMENT_SALE_STATUSES = ['PENDIENTE', 'FACTURADO', 'PAGADO']
const INVOICE_PAYMENT_STATUSES = ['PENDIENTE', 'PARCIAL', 'PAGADA']
const FINANCIAL_SUPPORT_TYPES = [
  'FACTURA_CLIENTE',
  'FACTURA_PROVEEDOR',
  'SOPORTE_TRANSFERENCIA',
  'SOPORTE_PAGO',
  'COMPROBANTE_CONTABLE',
  'CONCILIACION',
  'OTRO',
]
const SHIPMENT_TRACE_TYPES = [
  'NOTA',
  'SEGUIMIENTO',
  'HITO',
  'NOVEDAD',
  'CAMBIO_ESTADO',
]
const SHIPMENT_PROVIDER_SERVICE_CODES = QUOTATION_SERVICE_CODES

module.exports = {
  QUOTATION_TRANSPORT_MODES,
  QUOTATION_MODALITIES,
  QUOTATION_BUSINESS_TYPES,
  QUOTATION_MATERIAL_CLASSES,
  QUOTATION_STATUSES,
  QUOTATION_CLOSURE_STATUSES,
  QUOTATION_SERVICE_CODES,
  QUOTATION_DOCUMENT_TYPES,
  SHIPMENT_OPERATIONAL_STATUSES,
  SHIPMENT_FINANCIAL_STATUSES,
  SHIPMENT_CLOSURE_STATUSES,
  SHIPMENT_DOCUMENT_TYPES,
  SHIPMENT_TASK_STATUSES,
  SHIPMENT_TASK_PRIORITIES,
  SHIPMENT_COST_STATUSES,
  SHIPMENT_COST_TYPES,
  SHIPMENT_SALE_STATUSES,
  INVOICE_PAYMENT_STATUSES,
  FINANCIAL_SUPPORT_TYPES,
  SHIPMENT_TRACE_TYPES,
  SHIPMENT_PROVIDER_SERVICE_CODES,
}
